VERSION_NUMBER = "1.0.6-beta"

BRAINROT2PY_MAPPINGS = {
    "before\s+gta6": "async",
    "gaensehosen": "return",
    "yap": "print",
    "rizz": "+",
    "No\s+Cap": "True",
    "Cap": "False",
    "let\s+him\s+cook": "while",
    "not\s+stonks": "raise",
    "lock\s+in": "from",
    "calc\s+is\s+short\s+for\s+calculator": "math",
    "chat\s+is\s+this\s+real": "if",
    "yo\s+chat": "elif",
    "only\s+in\s+ohio": "else",
    "just\s+put\s+the\s+fries\s+in\s+the\s+bag\s+bro": "break",
    "hawk": "try",
    "tuah": "except",
    "spit\s+on\s+that\s+thang": "finally",
    "minus\s+aura": "-",
    "bop": "def",
    "get\sin\sthere": "import",
    "skibidi": "class",
    "flex": "for",
    "edge": "continue",
    "sus": "assert",
    "pookie": "with",
    "ahh": "as",
    "GOAT": "global",
    "delulu": "del",
    "NPC": "None",
    "unc": "self",
    "huzz": "range",
    "sigma\s+twin": ">=",
    "beta\s+twin": "<=",
    "twin": "==",
    "sigma": ">",
    "beta": "<",
    "diddy": "in",
    "pluh": "pass",
}
