VERSION_NUMBER = "1.0.6-beta"

BRAINROT2PY_MAPPINGS = {
    "before\s+gta6": "async",
    "zitat\s+ende\s+gaensehosen": "return",
    "yap": "print",
    "rizz": "+",
    "no\s+cap": "True",
    "cap": "False",
    "let\s+him\s+cook": "while",
    "not\s+stonks": "raise",
    "lock\s+in": "from",
    "straight\s+to\s+jail": "exit",
    "calc\s+is\s+short\s+for\s+calculator": "math",
    "chat\s+is\s+this\s+real": "if",
    "yo\s+chat": "elif",
    "only\s+in\s+ohio": "else",
    "ich\s+muss\s+raus": "break",
    "hawk": "try",
    "tuah": "except",
    "spit\s+on\s+that\s+thang": "finally",
    "minus\s+aura": "-",
    "just\s+using\s+slang": "def",
    "get\sin\sthere": "import",
    "skibidi": "class",
    "just\s+put\s+the\s+fries\s+in\s+the\s+bag\s+bro": "for",
    "edge": "continue",
    "sus": "assert",
    "pookie": "with",
    "ass": "as",
    "GOAT": "global",
    "hans\s+get\s+se\s+flammenwerfer": "del",
    "NPC": "None",
    "unc": "self",
    "huzz": "range",
    "sigma\s+twin": ">=",
    "beta\s+twin": "<=",
    "twin": "==",
    "sigma": ">",
    "beta": "<",
    "diddy": "in",
    "pluh": "pass",
}
